### PR TITLE
Catch syntax errors when parsing coffeescript

### PR DESCRIPTION
**Pull request by masone**
hey matt

got feedback from codeclimate. we ran into a repo with syntax errors that crash clog completely. i worked around this by setting the `fileTokens` to an empty array. both token metrics now end up with a 0. 
i had to extract the `summary` to a separate function, because `analyze` got too big.

what do you think?

### CODE REVIEW

**Comment by mdiebolt** [comment]
I don't believe that your PR actually catches files with compilation errors. The `tokens` method from CoffeeScript outputs the tokens in your file regardless of whether the file is valid CoffeeScript.

I'm working on a change that will first check if the file compiles before doing the token analysis.

**Comment by masone** [comment]
Well it worked in the tests I wrote ;)
Looking forward to a better solution!

**Comment by mdiebolt** [comment]
I [released 2.0.0](https://github.com/mdiebolt/clog/releases/tag/v2.0.0) with support for describing compilation errors. Only a minor change from this PR. Thanks for giving me a good place to start!

**Comment by masone** [comment]
Yay! I'll integrate it right away. Welcome back and thanks!

**Comment by masone** [comment]
Released [codeclimate-clog v1.0.0.rc3](https://github.com/masone/codeclimate-clog/releases/tag/v1.0.0.rc3)

**Pull request closed without merging**
